/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.pushwoosh.geozones;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import com.pushwoosh.location.PushwooshLocation;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="PushwooshGeozones", id="com.pushwoosh.geozones")
public class PushwooshGeozonesModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "PushwooshGeozonesModule";
	private static final boolean DBG = TiConfig.LOGD;

    @Kroll.method
    public void startTrackingGeoPushes() {
        Log.d(LCAT, "start tracking geo pushes called");
        
        PushwooshLocation.startLocationTracking();
    }
    
    @Kroll.method
    public void stopTrackingGeoPushes() {
        Log.d(LCAT, "stop tracking geo pushes called");
        
        PushwooshLocation.stopLocationTracking();
    }
}

